version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - RAILS_ENV=development

  db:
    image: keinos/sqlite3:latest
    volumes:
      - db_data:/db

volumes:
  db_data:
