version: '3.8'
services:
  pokemon-api:
    container_name: pokemon-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker
    environment:
      API_URL: ${API_URL}
      REDIS_URL: ${REDIS_URL}
      RAILS_ENV: development

  db:
    image: keinos/sqlite3:latest
    volumes:
      - db_data:/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db_data:
  redis_data: